language: python

install:
  - pip install tox coveralls
matrix:
  include:
    - python: 3.7
      env:
          - ENV=docs
    - python: 3.6
      env:
          - ENV=py36-django21,py36-django22
    - python: 3.7
      env:
          - ENV=py37-django21,py37-django22
script:
  - tox -e $ENV
after_success:
  - coveralls
